In [1]:
# 범주가 2개인 경우
sex = ['male', 'male', 'female', 'male', 'female', 'female']

import numpy as np
sex_conv = np.zeros(6)  # numpy 배열 6개 0으로 채워짐 [0,0,0,0,0,0]
for cnt, x in enumerate(sex):
    if(x=='female'):
        sex_conv[cnt] = 1

print(sex_conv)

[0. 0. 1. 0. 1. 1.]


In [5]:
# 범주가 3개 이상인 경우는 One-Hot-Encoding을 사용해야한다.
# tensorflow.keras.utils 모듈의 to_categorical 함수 import
from tensorflow.keras.utils import to_categorical

# one-hot-encoding 적용
sex_cate = to_categorical(sex_conv)

print('  남', '여')
print(sex_cate)

  남 여
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


[3 1 2 1 2 3]


In [9]:
pclass_orig = np.array([3, 1, 2, 1, 2, 3])
print("numpy 배열")
print(pclass_orig)

# tensorflow.keras.utils 모듈의 to_categorical 함수 import 
from tensorflow.keras.utils import to_categorical

# (0,1,2의 값을 가지도록) 1을 뺀 후, one-hot-encoding 적용
pclass_cate = to_categorical(pclass_orig - 1)

print("\none-hot-encoding")
print(pclass_cate)

numpy 배열
[3 1 2 1 2 3]

one-hot-encoding
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
